name: dismantlorapp
description: A mobile app for dismantling hurdles

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
  flutter_bloc: ^6.1.1
  meta: ^1.2.4
  equatable: ^1.2.5
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0
  get_it: ^5.0.4
  rxdart: ^0.25.0
  uuid: ^2.2.2
  path_provider: ^1.6.27
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
